os:
  - osx
  
env:
  - QTVER=5.9.0
  
language: cpp
  
compiler:
  - clang
  
cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt mpv; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/Cellar/qt/$QTVER/bin/qmake orion.pro; fi
  - make
  - cd ..
  - bash distfiles/deploy_mac.sh
