os:
  - osx
  
env:
  - QTVER=5.9.0
    QTBREWVER=5.9
  
language: cpp
  
compiler:
  - clang
  
cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt@$QTBREWVER jq; fi

script:
  - export QTDIR=$(brew info --json=v1 qt | jq -r '.[0].bottle.stable.cellar + "/" + .[0].name + "/" + .[0].installed[0].version')
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $QTDIR/bin/qmake orion.pro CONFIG+=multimedia; fi
  - make
  - bash distfiles/deploy_mac.sh
  - mkdir -p artifacts
  - zip -vr artifacts/orion.app.zip orion.app/
  
deploy:
  - provider: releases
    # To use this, create a Github token with the "public_repo" permission, and create an env var GITHUB_API_KEY in the Travis' project settings' environment, making sure "Display value in build log" is set to OFF
    api_key: '$GITHUB_API_KEY'
    file: 'artifacts/orion.app.zip'
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: "$AWS_S3_BUCKET"
    region: "$AWS_REGION"
    # Example policy to allow writes to bucket
    # {
    #     "Version": "2012-10-17",
    #     "Statement": [
    #         {
    #             "Effect": "Allow",
    #             "Action": "s3:PutObject",
    #             "Resource": "arn:aws:s3:::rakslice-orion-builds/*"
    #         }
    #     ]
    # }	
    local_dir: artifacts
    skip_cleanup: true
    on:
      all_branches: true
