os:
  - osx
  
env:
  - QTBREWVER=5.9
  
language: cpp
  
compiler:
  - clang
  
cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt@$QTBREWVER jq; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export QTDIR=$(brew info --json=v1 qt | jq -r '.[0].bottle.stable.cellar + "/" + .[0].name + "/" + .[0].installed[0].version'); fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export ORIONCONFIG=multimedia; fi
  - $QTDIR/bin/qmake orion.pro CONFIG+=$ORIONCONFIG
  - make
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash distfiles/deploy_mac.sh; fi
  - mkdir -p artifacts
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then zip -vr --symlinks artifacts/orion.app.zip orion.app/; fi
  
deploy:
  - provider: releases
    # To use this, create a Github token with the "public_repo" permission, and create an env var GITHUB_API_KEY in the Travis' project settings, making sure "Display value in build log" is set to OFF
    api_key: '$GITHUB_API_KEY'
    file: 'artifacts/orion.app.zip'
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
    # To use this, create an AWS S3 bucket with public read access, create IAM policy with the text below replacing the placeholder with the bucket name, 
    # create an AWS user for automation (with access key/secret) and give them that IAM policy, and set the env vars indicated in the Travis' project settings, making sure "Display value in build log" is set to OFF
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: "$AWS_S3_BUCKET"
    region: "$AWS_REGION"
    # Example policy to allow writes to a bucket
    # {
    #     "Version": "2012-10-17",
    #     "Statement": [
    #         {
    #             "Effect": "Allow",
    #             "Action": "s3:PutObject",
    #             "Resource": "arn:aws:s3:::BUCKET-NAME-GOES-HERE/*"
    #         }
    #     ]
    # }	
    local_dir: artifacts
    skip_cleanup: true
    on:
      all_branches: true
