os:
  - osx
  
env:
  - QTVER=5.9.0
  
language: cpp
  
compiler:
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt; fi

script:
  - set QMAKE=qmake
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then set QMAKE=/usr/local/Cellar/qt/$QTVER/bin/qmake; fi
  - cd src
  - $QMAKE orion.pro
  - make
  - cd ..
  - bash distfiles/deploy_mac.sh
